// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkbox': string;
  'checkbox-value': string;
  'title': string;
}
declare const cssExports: CssExports;
export = cssExports;
